{{- if .Values.basechart.configmapEnv }}
{{- range .Values.basechart.configmapEnv }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
data:
  {{- .data | nindent 2 }}
{{- end }}
{{- end }}